name: Test BusyBox

on:
  workflow_dispatch:

jobs:
  run_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test BusyBox Commands
        run: |
          mv ./busybox_arm64_static ./busybox

          file ./busybox
          du -h ./busybox
          otool -L ./busybox
          
          ./busybox --help
          ./busybox ash -c 'echo $(( 1 + 1 ))'
