name: Test BusyBox

on:
  workflow_dispatch:

jobs:
  run_test:
    strategy:
      matrix:
        os: [macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test BusyBox Commands
        run: |
          uname -a
        
          mv ./busybox_$(uname -m)_static ./busybox

          file ./busybox
          du -h ./busybox
          otool -L ./busybox

          ./busybox --help
          ./busybox ash -c 'echo $(( 1 + 1 ))'
